apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
      annotations:
        vault.security.banzaicloud.io/vault-addr: "http://vault.vault.svc.cluster.local:8200"

        # Delete this annotation to enable mutations
        vault.security.banzaicloud.io/mutate: "skip"
    spec:
      containers:
        - name: echo
          image: ghcr.io/sagikazarmark/http-echo2:v0.2.0
          env:
            - name: AWS_ACCESS_KEY_ID
              value: vault:secret/data/accounts/aws#AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-aws
                  key: secret-key
          envFrom:
            - configMapRef:
                name: demo-mysql
          ports:
            - containerPort: 8080
